"""
Fichier : disposable_domains.py
Dossier : backend/utils/
Description :
    Liste noire des domaines d'emails jetables / temporaires.
    Mise à jour manuelle — couvre les services les plus utilisés.
    Source : compilation des listes publiques connues.
"""

DISPOSABLE_DOMAINS = {
    # Mailinator et variantes
    "mailinator.com", "mailinator2.com", "mailinator.net",
    "suremail.info", "spamgourmet.com", "spamgourmet.net",

    # Guerrilla Mail
    "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
    "guerrillamail.biz", "guerrillamail.de", "guerrillamail.info",
    "grr.la", "guerrillamailblock.com", "spam4.me",

    # 10 Minute Mail et variantes
    "10minutemail.com", "10minutemail.net", "10minutemail.org",
    "10minutemail.de", "10minutemail.co.uk", "10minemail.com",
    "10minutemail.cf", "10minutemail.ga", "10minutemail.gq",
    "10minutemail.ml", "10minutemail.tk",

    # Temp Mail
    "tempmail.com", "temp-mail.org", "tempmail.net",
    "tempmail.io", "tempr.email", "tempinbox.com",
    "throwam.com", "throwam.net",

    # Yopmail
    "yopmail.com", "yopmail.fr", "cool.fr.nf", "jetable.fr.nf",
    "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr",
    "courriel.fr.nf", "moncourrier.fr.nf", "monemail.fr.nf",
    "monmail.fr.nf",

    # Autres services populaires
    "trashmail.com", "trashmail.at", "trashmail.io",
    "trashmail.me", "trashmail.net", "trashmail.org",
    "dispostable.com", "disposablemail.com",
    "fakeinbox.com", "fakeinbox.net",
    "maildrop.cc", "mailnull.com",
    "spamfree24.org", "spamfree24.de", "spamfree24.eu",
    "spamfree24.info", "spamfree24.net", "spamfree24.com",
    "spamgob.com", "spamherelots.com", "spamhereplease.com",
    "spamhole.com", "spamify.com", "spamkill.info",
    "spaml.com", "spaml.de",
    "throwaway.email", "throwam.com",
    "mailnesia.com", "mailnesia.net",
    "mailexpire.com", "mailexpire.com",
    "filzmail.com", "filzmail.de",
    "throwam.com", "jetable.com", "jetable.net", "jetable.org",
    "netzidiot.de", "nospamfor.us", "nowmymail.com",
    "objectmail.com", "obobbo.com", "odnorazovoe.ru",
    "oneoffemail.com", "onewaymail.com", "online.ms",
    "oopi.org", "opayq.com", "ordinaryamerican.net",
    "otherinbox.com", "ourklips.com", "outlawspam.com",
    "ovpn.to", "owlpic.com",
    "pancakemail.com", "paplease.com", "pcusers.otherinbox.com",
    "pepbot.com", "pfui.ru", "phentermine-mortgages.com",
    "pimpedupmyspace.com", "pingir.com", "pisoszi.com",
    "plexolan.de", "poczta.onet.pl", "politikerclub.de",
    "poofy.org", "pookmail.com",
    "privacy.net", "privatdemail.net",
    "proxymail.eu", "prtnx.com",
    "punkass.com", "putthisinyourspamdatabase.com",
    "qq.com",  # souvent utilisé pour le spam
    "rcpt.at", "recode.me", "recursor.net",
    "recyclemail.dk", "regbypass.com", "regbypass.comsafe-mail.net",
    "rejectmail.com", "rklips.com", "rmqkr.net",
    "rppkn.com", "rtrtr.com",
    "s0ny.net", "safe-mail.net", "safetymail.info",
    "safetypost.de", "sandelf.de", "saynotospams.com",
    "schafmail.de", "schrott-email.de", "secretemail.de",
    "secure-mail.biz", "selfdestructingmail.com",
    "sendspamhere.com", "senseless-entertainment.com",
    "seriously.im", "sharedmailbox.org",
    "sharklasers.com", "shieldemail.com", "shiftmail.com",
    "shitmail.de", "shitmail.me", "shitmail.org",
    "shitware.nl", "shortmail.net",
    "sibmail.com", "sinnlos-mail.de",
    "skeefmail.com", "slapsfromlastnight.com",
    "slaskpost.se", "slave-auctions.net",
    "slopsbox.com", "slushmail.com",
    "smellfear.com", "snakemail.com",
    "sneakemail.com", "sneakmail.de",
    "snkmail.com", "sofimail.com",
    "sofort-mail.de", "sogetthis.com",
    "soodonims.com", "spam.la",
    "spam.mn", "spam.su",
    "spam4.me", "spamavert.com",
    "spambob.com", "spambob.net",
    "spambob.org", "spambog.com",
    "spambog.de", "spambog.ru",
    "spambooger.com", "spambox.info",
    "spambox.irishspringrealty.com", "spambox.us",
    "spamcannon.com", "spamcannon.net",
    "spamcero.com", "spamcon.org",
    "spamcorptastic.com", "spamcowboy.com",
    "spamcowboy.net", "spamcowboy.org",
    "spamday.com", "spamex.com",
    "spamfree.eu",
    "spamgoes.in", "spamgourmet.com",
    "spamgourmet.net", "spamgourmet.org",
    "spamherelots.com", "spamhereplease.com",
    "spamhole.com",
    "spoofmail.de", "stuffmail.de",
    "super-auswahl.de", "supergreatmail.com",
    "supermailer.jp", "superrito.com",
    "superstachel.de", "suremail.info",
    "svk.jp", "sweetxxx.de",
    "tafmail.com", "tagyourself.com",
    "talkinator.com", "tapchicuocsong.net",
    "tefl.ro", "teleworm.com",
    "teleworm.us", "temp-mail.ru",
    "temp.emeraldwebmail.com", "temp.headstrong.de",
    "tempalias.com", "tempinbox.co.uk",
    "tempmail.de", "tempmail.eu",
    "tempmail.us", "tempmailer.com",
    "tempmailer.de", "temporarily.de",
    "temporaryemail.net", "temporaryemail.us",
    "temporaryforwarding.com", "temporaryinbox.com",
    "temporarymailaddress.com", "tempsky.com",
    "tempthe.net", "tempymail.com",
    "thanks2book.com", "thc.st",
    "thecloudindex.com",
    "thelimestones.com", "themailpro.com",
    "thenullemail.com", "thisisnotmyrealemail.com",
    "thismail.net", "thismail.ru",
    "throwam.com",
    "tilien.com", "tittbit.in",
    "tizi.com", "tm.in.th",
    "tmailinator.com", "toiea.com",
    "toomail.biz", "topranklist.de",
    "torchmail.com", "tradermail.info",
    "trash-amil.com", "trash-mail.at",
    "trash-mail.cf", "trash-mail.com",
    "trash-mail.de", "trash-mail.ga",
    "trash-mail.gq", "trash-mail.io",
    "trash-mail.ml", "trash-mail.tk",
    "trash2009.com", "trash2010.com",
    "trash2011.com", "trashdevil.com",
    "trashdevil.de", "trashemail.de",
    "trashmail.at", "trashmail.com",
    "trashmail.io", "trashmail.me",
    "trashmail.net", "trashmail.org",
    "trashmail.xyz",
    "trashmailer.com", "trashymail.com",
    "trbvm.com", "trillianpro.com",
    "trmailbox.com", "tropicalbass.info",
    "tryalert.com", "turual.com",
    "twinmail.de", "tyldd.com",
    "ubm.md", "uggsrock.com",
    "umail.net", "unids.com",
    "upliftnow.com", "uplipht.com",
    "uroid.com", "us.af",
    "username.e4ward.com", "utiket.us",
    "uu.gl", "uwork4.us",
    "valemail.net", "venompen.com",
    "veryrealemail.com", "vidchart.com",
    "viditag.com", "viewcastmedia.com",
    "viewcastmedia.net", "viewcastmedia.org",
    "viralplays.com", "vmail.me",
    "vomoto.com", "vpn.st",
    "vubby.com", "w3internet.co.uk",
    "walala.org", "walkmail.net",
    "watchever.biz",
    "webemail.me", "webm4il.info",
    "webmail.kolmpuu.net", "webprogramming.com",
    "websitefinances.com", "wegwerfadresse.de",
    "wegwerfemail.com", "wegwerfemail.de",
    "wegwerfmail.de", "wegwerfmail.info",
    "wegwerfmail.net", "wegwerfmail.org",
    "wh4f.org", "whyspam.me",
    "wickmail.net", "wilemail.com",
    "will-hier-weg.de", "willhackforfood.biz",
    "willselfdestruct.com", "winemaven.info",
    "wronghead.com", "wuzupmail.net",
    "www.e4ward.com", "www.gishpuppy.com",
    "www.mailinator.com", "wwwnew.eu",
    "x.ip6.li", "xagloo.co",
    "xagloo.com", "xemaps.com",
    "xents.com", "xmaily.com",
    "xoxy.net", "xsmail.com",
    "xuimail.com", "xyzfree.net",
    "ya.ru",  # souvent abusé
    "yapped.net", "yeah.net",
    "yep.it", "yogamaven.com",
    "yopmail.fr", "yopmail.com",
    "youmailr.com", "ypmail.webarnak.fr.eu.org",
    "yuurok.com",
    "z1p.biz", "za.com",
    "zebins.com", "zebins.eu",
    "zehnminuten.de", "zehnminutenmail.de",
    "zetmail.com", "zippymail.info",
    "zoaxe.com", "zoemail.com",
    "zoemail.net", "zoemail.org",
    "zomg.info",
}


def is_disposable_domain(email: str) -> bool:
    """
    Retourne True si le domaine de l'email est dans la liste noire.
    """
    try:
        domain = email.strip().lower().split("@")[1]
        return domain in DISPOSABLE_DOMAINS
    except (IndexError, AttributeError):
        return False
